version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3.13-alpine
    container_name: 'rabbitmq'
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - 5672:5672
      - 15672:15672
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:15672']
      interval: 50s
      timeout: 10s
      retries: 5
    volumes:
      - 'rabbitmqdata:/var/lib/rabbitmq/data'
      - 'rabbitmqdata:/var/lib/rabbitmq/log'
  
  database:
    image: postgres:16.1-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: vilnius4kids
    ports:
      - '5435:5432'
    volumes:
      - vilnius4kids-db:/var/lib/postgresql/data

  server:
    platform: linux/amd64
    build:
      context: .
      dockerfile: ./server/Dockerfile
    env_file:
      - ./server/.env
    environment:
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: vilnius4kids
      DB_SSL: false
      DB_HOST: database
      RABBIT_MQ_USER: guest
      RABBIT_MQ_PASSWORD: guest
      RABBIT_MQ_HOST: rabbitmq
    ports:
      - '3000:3000'
    depends_on:
      rabbitmq:
        condition: service_healthy
      database:
        condition: service_healthy

  client:
    platform: linux/amd64
    build:
      context: .
      dockerfile: ./client/Dockerfile
      args:
        VITE_API_ORIGIN: http://localhost:3001
        VITE_API_PATH: /api/v1/trpc
        VITE_AWS_S3_FILE_TYPES_ALLOWED: image/jpeg
        VITE_AWS_S3_FILE_SIZE_MAX_IN_BYTES: 1000000
    environment:
      API_PROXY_PASS: http://server:3000
    ports:
      - '3001:80'
    depends_on:
      - server

volumes:
  vilnius4kids-db:
  rabbitmqdata:
