name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16.1-alpine
        env:
          # Postgres will create a database with the following credentials
          POSTGRES_USER: ${{ secrets.DB_USER }}
          POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
    env:
      TOKEN_KEY: ${{ secrets.TOKEN_KEY }}
      TOKEN_EXPIRES_IN: 1h
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Node
      uses: actions/setup-node@v4
      with:
        node-version: 18
        cache: 'npm'

    - name: Install server dependencies
      run: npm ci

    - name: Type check server
      run: npm run typecheck -w=server

    - name: Lint server
      run: npm run lint -w=server

    - name: Test server
      run: npm run test -w=server

    - name: Build server
      run: npm run build -w=server

    - name: Start server
      run: npm run start -w=server &
      env:
          # Pass the same credentials to our server environment variables, just like
          # we would if we had an .env file.
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: testdb

          # port to start the server on
          PORT: 3000

    - name: Health probe
      uses: Jtalk/url-health-check-action@v3.2
      with:
        max-attempts: 5
        retry-delay: 5s
        url: http://localhost:3000/health
    
    - name: Readiness probe
      uses: Jtalk/url-health-check-action@v3.2
      with:
        max-attempts: 5
        retry-delay: 5s
        url: http://localhost:3000/ready
